theme = 'neovim'

[keybinds]
close = ["Escape", "ctrl q"]
next = ["Down", "ctrl n"]
previous = ["Up", "ctrl p"]
left = ["Left", "ctrl h"]
right = ["Right", "ctrl l"]
down = ["Down", "ctrl j"]
up = ["Up", "ctrl k"]
toggle_exact = ["ctrl e"]


[providers]
default = [
  "desktopapplications",
]

[providers.actions]
desktopapplications = [
  { action = "pin", bind = "ctrl shift p", after = "AsyncReload" },
  { action = "unpin", bind = "ctrl shift p", after = "AsyncReload" },
]

clipboard = [
  { action = "pause", bind = "ctrl shift p" },
  { action = "unpause", bind = "ctrl shift p" },
]

